# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build files and transfer to FTP

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: prod or stage
        required: true
        default: stage

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run ${{ github.event.inputs.build-type }}-build --if-present
    - run: npm run ${{ github.event.inputs.build-type }}-logic --if-present
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_ADDRESS }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/${{ github.event.inputs.build-type }}/
        server-dir: ./bcplugins/checkoutlistener-${{ github.event.inputs.build-type }}/
        dangerous-clean-slate: true
